version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-tdd-finances-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist/:/usr/repos/clean-tdd-finances/dist/
      - ./package.json:/usr/repos/clean-tdd-finances/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
     - mongo